import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = fs.readFileSync(new URL('../source/electron/main.mjs', import.meta.url), 'utf8')
const preload = fs.readFileSync(new URL('../source/electron/preload.cjs', import.meta.url), 'utf8')
assert.match(source, /contextIsolation:\s*true/)
assert.match(source, /nodeIntegration:\s*false/)
assert.match(source, /sandbox:\s*true/)
assert.match(source, /ELECTRON_RUN_AS_NODE/)
assert.match(source, /127\.0\.0\.1/)
assert.match(source, /requestSingleInstanceLock/)
assert.match(source, /existsSync\(path\.join\(packagedRuntime, 'server\.mjs'\)\)/)
assert.doesNotMatch(source, /app\.isPackaged\s*\?/) 
assert.doesNotMatch(source, /openExternal\(`http:\/\/127\.0\.0\.1/)
assert.match(source, /preload:\s*path\.join\(here, 'preload\.cjs'\)/)
assert.match(source, /brainana:profiles:list/)
assert.match(source, /brainana:remote:connect/)
assert.match(source, /brainana:remote:cancel-connect/)
assert.match(source, /ControlPersist=600/)
assert.doesNotMatch(source, /-fNT/)
assert.match(preload, /contextBridge\.exposeInMainWorld\('brainanaDesktop'/)
assert.doesNotMatch(preload, /node:fs|child_process/)
console.log('Electron desktop source checks passed')
