#!/usr/bin/env node
// Emits the single source of version + build id (default: packages/core-server/version.mjs).
// Replaces the old triplicate hardcoding in server.mjs, launcher, and VERSION.json (finding R6).
// Version comes from a package.json; buildId from the current git commit + date when available,
// falling back to a package-version stamp so the build is reproducible without git.
//
// Parametrised per tool so each app can emit its own identity (multi-tool workspace):
//   --app <name>          app identity string (default: brainana-viewer)
//   --version-from <path>  package.json to read the version from (default: repo root)
//   --out <path>           where to write version.mjs (default: packages/core-server/version.mjs)
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const argv = process.argv.slice(2)
function arg(name, fallback) {
  const i = argv.indexOf(name)
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : fallback
}
const appName = arg('--app', 'brainana-viewer')
const versionFrom = path.resolve(root, arg('--version-from', 'package.json'))
const dest = path.resolve(root, arg('--out', path.join('packages', 'core-server', 'version.mjs')))

const pkg = JSON.parse(readFileSync(versionFrom, 'utf8'))
const version = pkg.version

// Prefer a git tag/commit for the build id; degrade gracefully outside a git checkout.
function gitBuildId() {
  try {
    const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
    const tag = (() => {
      try {
        return execFileSync('git', ['describe', '--tags', '--always'], { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
          .toString()
          .trim()
      } catch {
        return sha
      }
    })()
    return `${tag}-${sha}`
  } catch {
    return null
  }
}

const date = new Date().toISOString().slice(0, 10) // YYYY-MM-DD
const buildId = process.env.BRAINANA_BUILD_ID || gitBuildId() || `v${version}-${date}`

const banner = '// GENERATED by scripts/generate-version.mjs — do not edit by hand.\n'
const body = `export const APP_NAME = ${JSON.stringify(appName)}
export const APP_VERSION = ${JSON.stringify(version)}
export const BUILD_ID = ${JSON.stringify(buildId)}
export const versionInfo = Object.freeze({ app: APP_NAME, version: APP_VERSION, buildId: BUILD_ID })
`

writeFileSync(dest, banner + body)
console.log(`generate-version: wrote ${path.relative(root, dest)} (version ${version}, build ${buildId})`)
